# Generated by Django 3.2.2 on 2021-06-09 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_payment_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
