# Generated by Django 3.2.2 on 2021-06-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210609_1037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
